name: JOURDAN - Fridays1705

on:
  repository_dispatch:
    types:  [JOURDAN]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install libraries
        run: pip install mailjet_rest
             pip install requests
             pip install datetime
             pip install pygsheets
      - name: execute JOURDAN script
        run: |
          python JOURDAN/JOURDAN.py
