name: SAKHAROV - Weekdays1505

on:
  repository_dispatch:
    types:  [SAKHAROV]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install libraries
        run: pip install selenium
             pip install requests
             pip install datetime
             pip install pygsheets
      - name: execute SHERLOCK script
        run: |
          python SAKHAROV/SHERLOCK/SHERLOCK.py
      - name: execute LinkedIn script
        run: |
          python SAKHAROV/ROOMBA/Scraper-LinkedIn.py


          
